"""init models

Revision ID: 4fc8a9aa5df1
Revises: 
Create Date: 2026-05-16 22:09:56.266845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc8a9aa5df1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('xgen_balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.String(), nullable=False),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('max_hp', sa.Integer(), nullable=False),
    sa.Column('base_armor', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ships_id'), ['id'], unique=False)

    op.create_table('expeditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('zone_config_id', sa.String(), nullable=False),
    sa.Column('zone_risk', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CLAIMED', 'DAMAGED', 'DESTROYED', name='expeditionstatus'), nullable=True),
    sa.Column('loot_resources', sa.String(), nullable=True),
    sa.Column('loot_rare', sa.String(), nullable=True),
    sa.Column('damage_taken', sa.Integer(), nullable=True),
    sa.Column('is_destroyed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['ship_id'], ['ships.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expeditions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expeditions_id'))

    op.drop_table('expeditions')
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ships_id'))

    op.drop_table('ships')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_players_id'))

    op.drop_table('players')
    # ### end Alembic commands ###
