"""update models for expedition service v2

Revision ID: 6ee6fa616262
Revises: 
Create Date: 2026-05-17 13:57:20.693182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ee6fa616262'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('zone_config_id', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('zone_risk', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('loot_resources', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('loot_rare', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_destroyed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'active', 'completed', 'claimed', name='expeditionstatus'),
               nullable=False)
        batch_op.drop_column('loot')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('started_at')
        batch_op.drop_column('tier')
        batch_op.drop_column('ends_at')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('xgen_balance',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('base_armor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('hp', sa.Integer(), nullable=True))
        batch_op.drop_column('health_current')
        batch_op.drop_column('rank')
        batch_op.drop_column('health_max')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('health_max', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rank', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('health_current', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('hp')
        batch_op.drop_column('max_hp')
        batch_op.drop_column('base_armor')
        batch_op.drop_column('is_active')
        batch_op.drop_column('tier')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.alter_column('xgen_balance',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ends_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tier', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'active', 'completed', 'claimed', name='expeditionstatus'),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_destroyed')
        batch_op.drop_column('loot_rare')
        batch_op.drop_column('loot_resources')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('zone_risk')
        batch_op.drop_column('zone_config_id')

    # ### end Alembic commands ###
