"""paler_xp

Revision ID: eff7d1de5bbe
Revises: a861c82b7aa1
Create Date: 2026-05-17 12:12:59.986937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eff7d1de5bbe'
down_revision: Union[str, Sequence[str], None] = 'a861c82b7aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipe_hash', sa.String(length=64), nullable=False),
    sa.Column('artifact_id', sa.UUID(), nullable=False),
    sa.Column('discoverer_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['discoverer_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_hash')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('effect', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('cycles_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('rarity',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_artifacts_id'))
        batch_op.drop_constraint(batch_op.f('artifacts_player_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('crafted_at')
        batch_op.drop_column('effect_json')
        batch_op.drop_column('is_equipped')
        batch_op.drop_column('name_en')
        batch_op.drop_column('config_id')
        batch_op.drop_column('name_ru')

    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ends_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('loot', sa.JSON(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('ship_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_expeditions_id'))
        batch_op.drop_constraint(batch_op.f('expeditions_player_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('expeditions_ship_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'ships', ['ship_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('loot_resources')
        batch_op.drop_column('zone_config_id')
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('zone_risk')
        batch_op.drop_column('end_time')
        batch_op.drop_column('loot_rare')
        batch_op.drop_column('start_time')
        batch_op.drop_column('is_destroyed')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('xp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pilot_rank', sa.String(length=16), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('telegram_id',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('xgen_balance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_players_id'))
        batch_op.drop_column('last_craft_at')

    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('rank', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('materia', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('speed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('health_max', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('health_current', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index(batch_op.f('ix_ships_id'))
        batch_op.drop_constraint(batch_op.f('ships_player_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['player_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('max_hp')
        batch_op.drop_column('tier')
        batch_op.drop_column('base_armor')
        batch_op.drop_column('is_active')
        batch_op.drop_column('config_id')
        batch_op.drop_column('hp')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hp', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('config_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('base_armor', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tier', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_hp', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ships_player_id_fkey'), 'players', ['player_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_ships_id'), ['id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('player_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('health_current')
        batch_op.drop_column('health_max')
        batch_op.drop_column('status')
        batch_op.drop_column('speed')
        batch_op.drop_column('materia')
        batch_op.drop_column('rank')
        batch_op.drop_column('name')

    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_craft_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_players_id'), ['id'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('xgen_balance',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('telegram_id',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('pilot_rank')
        batch_op.drop_column('xp')

    with op.batch_alter_table('expeditions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_destroyed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('loot_rare', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('zone_risk', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('zone_config_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('loot_resources', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expeditions_ship_id_fkey'), 'ships', ['ship_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('expeditions_player_id_fkey'), 'players', ['player_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_expeditions_id'), ['id'], unique=False)
        batch_op.alter_column('ship_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('loot')
        batch_op.drop_column('ends_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('duration_minutes')
        batch_op.drop_column('tier')

    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_ru', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('config_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name_en', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_equipped', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('effect_json', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('crafted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('artifacts_player_id_fkey'), 'players', ['player_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_artifacts_id'), ['id'], unique=False)
        batch_op.alter_column('rarity',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('player_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('cycles_remaining')
        batch_op.drop_column('effect')
        batch_op.drop_column('name')

    op.drop_table('recipes')
    # ### end Alembic commands ###
